# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: build programing
        run: |
          go build -v
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: SCP Files
        # You may pin to the exact commit or the version.
        # uses: appleboy/scp-action@b476d5806f2a4c1ed5902a87fa91b0623cac7258
        uses: appleboy/scp-action@v0.0.1
        env:
           WELCOME: "ssh scp ssh pipeline"
           LASTSSH: "Doing something after copying"
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.NAME }}
           password: ${{ secrets.PASS }}
           port: ${{ secrets.PORT }}
           source: "projection.exe"
           target: "/home/www"
      # -----哈哈哈哈哈
